### ISSUE TITLE
composer-cli blueprint functions not respecting show_json parameter

### ISSUE THREAD

**Issue by atodorov** [weldr/lorax#1022]
For example ` blueprints_freeze_show`:
https://github.com/weldr/lorax/blob/master/src/composer/cli/blueprints.py#L477

There is the `show_json` parameter in the signature but it is never used inside the function body. It always requests TOML from the server. Probably others too. 

On a related not pylint is supposed to warn about unused parameters/unused variables, not sure why it doesn't.

**Comment by bcl** [comment]
That's not exactly a bug, think of it as encouragement not to use --json for anything other than interactive debugging :)

The arguments to all the functions are same because they are all dispatched from one place, so even if it was warning it would then have to be turned off.

**Comment by bcl** [comment]
I took a quick look and yes, there are several places where it doesn't return json, also several where it doesn't accept json for pushing things to the server. The `--json` option has always just been there for debugging, not so that it can act as an interface to the API for scripts. I've updated the docs in PR #1024 to make this more clear.
