### ISSUE TITLE
installer: Using fallocate is dangerous for raw image: it will corrupt the disk image

### ISSUE THREAD

**Issue by pmarzin** [weldr/lorax#1227]
Hello all Lorax team,

This is my first contribution here. Nice to meet you!

I use to work with "livemedia-creator" to make a raw image file of a disk using CI management tools to automate creation, tests and validation of the generated image.

**Problem :**
With a specific test, we wrote the raw image on a device that was previously filled of "1" data. By doing this we detect that the "0" data were not written on the device. Instead, they were replacing by "holes". So, on the flashed device, all installed binaries were missing their mandatory "0" data inside them.
For example: the GPT table partition written into the raw image is ~17KB total of data. They are mapped like this: ~5KB of non "0" data followed by ~12KB of "0" data. On this particular case, using `fallocate --dig-holes` on the raw image file will replace the mandatory "0" data by holes into it. Then, when flashing the raw image file on device, the ~12K of "0" data are not written (as they have been replaced by "holes"). The result is: on the flashed device, the GPT table partition is corrupted.
This is an example with the GPT partition but, it appears with all binary that contains "0" mandatory data (like the uncompressed kernel).

**Consequences :**
We then finally detect that this line https://github.com/weldr/lorax/blob/f6e8518ec9105a292d734786ad3813197922ca14/src/pylorax/installer.py#L537 was doing the tricks to convert "0" data into "holes". The usage is risky because `fallocate` will just replace the 0 by holes into the file. The holes will be well understood by the host file system. So when reading the file, all is good. The sparse file is well managed by the OS. OK. **But**, when flashing it on a device, the host OS read the holes and as they are holes it not write them on the device! That create the corrupted image because the mandatory "0" data is not written on the device.

**Solutions :**
In this case we have 3 solutions:
- flash the device without exploiting the sparse feature (ex: flash all holes like "0" data). This could be **very** slow!
- accept that the image is a bit bigger and don't convert mandatory "0" using `fallocate`.
- I'm open to any better suggestion :)

**Comment by jobol** [comment]
The tool `BMAPTOOL` (https://manpages.ubuntu.com/manpages/trusty/man1/bmaptool.1.html) is used to flash images without flashing unused parts. It speeds flashing time. To achieve that, `BMAPTOOL` scan image files, detect holes and map them. The use of `fallocate --dig-holes` creates false holes. That is bad. As Pierre wrote, GPT tables are not correctly initialized and even linux kernel is not correctly written because ranges of zeros are replaced by holes and then, when flashed, by garbage.

**Comment by bcl** [comment]
Interesting, I haven't run into this before. The reason why we are punching holes is to keep the image size down, so it really isn't something we're likely to change. Is the bmaptool what you are using when you see this problem? I generally use dd when writing to flash myself, so that may be why I haven't seen any reports of this. We also have a media test that can be run when it boots, and I would expect to see that fail if the 0's were skipped.

**Comment by jobol** [comment]
Yes it is because we use `bmaptool`. When we use `dd` (without `conv=sparse`) there is no defect (but writing flash memories is much longer).

Without the option `--dig-holes`, we can see the image is not much bigger because creation operations made on it are maintaining significant holes. You can check that using `du`. Try to create an image without option ` --dig-holes` and use `du` to check the real gain. We have found that it is light.

**Comment by jobol** [comment]
Also, note that flashing with `bmaptool`in more than increasing speed also increases life of flash memories by only writing significant parts and reduces heat.

**Comment by bcl** [comment]
Looking at a minimal disk image I see it saving about 3MiB, most of the savings is due to `fstrim` (about 137MiB). So it's not a trivial amount of space saved. FYI we log the size using `du -B1` in program.log for the image side before `fstrim`, after `fstrim` and after `fallocate`.

I'm also not sure what the alternative is? If `fallocate` is removed then there are no holes and there is no potential benefit to using `bmaptool` anyway, so why not take the safe path and use `dd`?

**Comment by jobol** [comment]
I agree the use of `fstrim`but not the use of `--dig-holes`in `fallocate`. You showed the gain are very little (3MiB versus 137MiB).

IMHO, at the end, after compression (xz knows holes and keep track of it, but also compress really efficiently zeros) the size will be nearly the same with or without `fallocate`.

I'm still advocating the removal of `--dig-holes' that is not safe.

**Comment by pmarzin** [comment]
Yes, currently `fstrim` saves a lot of space. Not `fallocate`. Moreover, I confirm that without `fallocate` the raw image file is still a sparse file. Because it is created as it first :
https://github.com/weldr/lorax/blob/f6e8518ec9105a292d734786ad3813197922ca14/src/pylorax/installer.py#L397
In our case we test with success that not using `fallocate` does not corrupt the raw image disk and then could be safely flashed with a sparse compliant tool (like `bmaptool`) that is saving lot of time. The raw image is still a sparse file with around 90% of holes.
