### ISSUE TITLE
Fedora 36 live iso errors

### ISSUE THREAD

**Issue by Athwale** [weldr/lorax#1261]
Hi,
I recently attempted to build a Fedora 36 live iso and I got a bunch of errors.
The image works, but I would like to know what the errors are and whether they can be safely ignored.

```
mock/builddir/anaconda/packaging.log:14:24:39,785 INF dnf.rpm: /var/tmp/rpm-tmp.YjcnfQ: line 2: ln: command not found
mock/builddir/livemedia.log:2022-08-26 14:17:20,258 INFO pylorax: ** (process:1): CRITICAL **: 14:17:19.855: Failed to create a new connection for the system bus: Could not connect: No such file or directory
mock/builddir/livemedia.log:2022-08-26 14:17:20,258 INFO pylorax: ** (process:1): CRITICAL **: 14:17:19.855: Failed to setup DBus connection: Could not connect: No such file or directory
mock/builddir/anaconda/packaging.log:14:27:30,846 INF dnf.rpm: sed: can't read /etc/default/grub: No such file or directory
mock/builddir/anaconda/dbus.log:** (process:9): CRITICAL **: 14:17:20.989: Failed to create a new connection for the system bus: Could not connect: No such file or directory
```
The last error repeats many times.

Thanks.

**Comment by bcl** [comment]
These are all error from Anaconda and DNF. The ln one is likely from an rpm script that assumes ln is available (it's from coreutils so it should be). The bus ones are because it is run inside a limited namespace and doesn't have access to the system dbus. AFAIK anaconda deals with this just fine and the errors can be ignored. The lack of an /etc/default/grub (and dnf or the rpm script) is likely because grub isn't installed yet. It's hard to tell where that actually comes from.

None of these are things that lorax can do anything about, it's up to Anaconda to have the right things installed at the right time, or for rpm scripts to check their assumptions.
