### ISSUE TITLE
Kernel Panic with rhel 9

### ISSUE THREAD

**Issue by Mordecaine** [weldr/lorax#1394]
Hello,

In the past, I created an image with rhel 8 with the following command:
```bash
/sbin/livemedia-creator --ks /opt/cloud_image_creation/ks-files/flattened_azure-redhat8.4.ks --make-disk --iso /opt/cloud_image_creation/iso-files/rhel-8.4-x86_64-dvd.iso --ram 2048 --vcpus 2 --resultdir /opt/cloud_image_creation/images/redhat_8.4azure-2024-05-01/image --project redhat --releasever 8.4 --logfile /opt/cloud_image_creation/images/redhat_8.4azure-2024-05-01/log_files/livemedia.log
```

Now I want to create a rhel 9 image. Furthermore I want, in the same time, switch to efi boot:
```bash
/sbin/livemedia-creator --ks /opt/cloud_image_creation/ks-files/flattened_azure-redhat9.ks --virt-uefi --make-disk --iso /opt/cloud_image_creation/iso-files/rhel-9.4-x86_64-boot.iso --ram 2048 --vcpus 2 --resultdir /opt/cloud_image_creation/images/redhat_9_azure-2024-05-02/image --project redhat --releasever 9 --logfile /opt/cloud_image_creation/images/redhat_9_azure-2024-05-02/log_files/livemedia.log
```
The installation progress stopped and so I checked with an VNC viewer, what happened:
![grafik](https://github.com/weldr/lorax/assets/25454900/14fa0df4-6cc2-499b-8754-64721e4f68e6)

There is a kernel Panic.

So I tested the same command, but I changed the iso image from rhel 9 to rhel 8:
```
/sbin/livemedia-creator --ks /opt/cloud_image_creation/ks-files/flattened_azure-redhat9.ks --virt-uefi --make-disk --iso /opt/cloud_image_creation/iso-files/rhel-8.9-x86_64-boot.iso --ram 2048 --vcpus 2 --resultdir /opt/cloud_image_creation/images/redhat_9_azure-2024-05-02/image --project redhat --releasever 9 --logfile /opt/cloud_image_creation/images/redhat_9_azure-2024-05-02/log_files/livemedia.log
```
After that, the installation process started (it failed because of the wrong kickstart file, but there was no kernel panic).

I got this problems with the following versions of livemedia-creator:
livemedia-creator-38.12-1
livemedia-creator-28.14.70-1

Is that a bug or is it not possible to create rhel 9 images with livemedia-creator or is the fault mine?

**Comment by bcl** [comment]
If you could move this bug report over to https://issues.redhat.com/ as a bug against lorax I would appreciate it (since it is related to RHEL it should be tracked there).
The error is that the RHEL9 iso requires x86-64-v2 instruction support. livemedia-creator uses qemu with cpu support set to match the host, so this would appear to mean your host system can't support those instructions. You can try using a different qemu cpu setting by passing `--cpu XXX` to livemedia-creator where XXX is one of the cpu values from `qemu-kvm -cpu help` this will likely effect the speed of the install though so it would probably be better to find a newer system with native support.
