### ISSUE TITLE
Unable to disable mediacheck / rd.live.check

### ISSUE THREAD

**Issue by williamtwomey** [weldr/lorax#1401]
I might be missing something, but I'm not seeing a way to avoid the mediacheck (rd.live.check) when using `livemedia-creator`

My kickstart does not contain `mediacheck` or `rd.live.check`

Was hoping I could just remove it from the templates in `/usr/share/lorax/templates.d` but that doesn't appear to have worked. Looks like anaconda will always include this.

Hoping that I can either change the default boot selection, or just disable this altogether. Any assistance would be greatly appreciated.

This is happening when generating a Rocky 9 ISO

```
livemedia-creator --ks /ks/rocky9.ks --no-virt --resultdir /var/lmc --project=Rocky9 --make-iso --volid Rocky-9 --iso-only --iso-name rocky9.iso --releasever=9 --nomacboot
```

**Comment by bcl** [comment]
The grub2 menu has 2 entries with the default being the one that includes rd.live.check, you can change it by copying the default templates from `/usr/share/lorax/templates.d` and either removing the whole entry, or by editing the config file in `live/config_files/x86/grub2-bios.cfg` and `live/config_files/x86/grub2-efi.cfg` to change `set default="1"` to a `"0"` instead.

I'm guessing that you edited the configs in `/usr/share/lorax/templates.d/99-generic/config_files` instead of the live ones in `/usr/share/lorax/templates.d/99-generic/live/config_files/`
