### ISSUE TITLE
Tell users to use url + repo if a kickstart only contains repo directives.

### ISSUE THREAD

**Issue by jflorian** [weldr/lorax#164]
New user to lm-c here; long time user of livecd-tools though.  I'm passing a kickstart that lcd-t was plenty happy with, but lm-c fails stating:

`Only url and nfs install methods are currently supported. Please fix your kickstart file.`

However, there are several directives in a kickstart that can accept such URIs and I'm given no hint as to which one I'm using against the needs of lm-c.  My initial encounter with this was via Koji so it was doubly obscure.  I'm now in the process of running lm-c directly from workstation so that I can hack the code to add some debug messages to learn what ks directive that condition is looking at.

**Comment by bcl** [comment]
If you are going to start with a livecd-creator kickstart you should read this first - https://rhinstaller.github.io/lorax/livemedia-creator.html#kickstarts but I'd recommend a current spin kickstart instead. livecd-creator kickstarts won't work with lmc without some changes.

livecd-tools never exactly tracked Anaconda so its kickstart parsing wasn't always what you'd see on a real system. Since lmc uses Anaconda you will see different behavior than you're used to with livecd-tools. Starting with one of the example kickstarts, or an official spin will save you a lot of confusion.

In this case the error means exactly what it says, you need to use the url or nfs install method in the kickstart, not just repo commands as was common with livecd-tools.

**Comment by jflorian** [comment]
Thanks Brian, that helps!  I've been using the essentially same kickstart for so long that I'd forgotten some of the syntax.  I might never have been confused if the message was worded more like:

`The "repo" install method is invalid; only "url" and "nfs" are currently supported. Please fix your kickstart file.`

I realize it's a subtle difference but that would have told me what I did wrong in addition to what I need to do instead.  Ideally it would point me to the line number at fault too.

I eventually wound up trying a current spin kickstart and managed to get it to work.  Though I'm having no luck with --no-virt because anaconda dies.  It looks like that may be due to /mnt/sysimage -- that conflicts with our use of automount which "owns" /mnt and won't allow anything else to mkdir there.  Has there been any thought to making ROOT_PATH configurable?  (I know of ROOT_PATH from /usr/sbin/lm-c, but I don't know if there are other components that have a similar assumption/hardcoded path.)

**Comment by bcl** [comment]
That's probably a good idea, I can make it check for the presence of repo w/o url and nfs. repo is still valid, but only when one of those 2 are also included.

Anaconda can take a path for --dirinstall but lmc hasn't been written to do that so it hasn't really been tested since I wrote it.

**Comment by bofh80** [comment]
I don't really have this setup in a dev env to test it myself yet. But would something like this work?

if opts.no_virt and ks.handler.method.method not in ("url", "nfs") \
and not ks.handler.ostreesetup.seen and ks.handler.repo.seen:
errors.append("Only repo found, please add url, nfs or ostreesetup install method."
"Please fix your kickstart file by adding nfs, url, ostreesetup." )
