### ISSUE TITLE
service fails to start if it can't connect to repository

### ISSUE THREAD

**Issue by andreasn** [weldr/lorax#487]
I'm building images that uses a repository that is on a private network. I use VPN to connect to it. Whenever I forget to log in to the VPN and try to build images, lorax-composer crashes on start, and I get a very cryptic message out of composer-cli.

**Comment by bcl** [comment]
Please open a bug on bugzilla with the composer.log from /var/lib/lorax-composer/ and whatever other output you can gather from the crash (maybe journalctl output?) I think we need to stat using bugzilla to track issues like this, since it's easier to attach logs and clone them to the various branches that may need to be fixed.

**Comment by andreasn** [comment]
Filed as https://bugzilla.redhat.com/show_bug.cgi?id=1717523
