### ISSUE TITLE
lorax-composer: sort order for /api/v0/modules/list/<module_names>[?offset=0&limit=20] 

### ISSUE THREAD

**Issue by jgiardino** [weldr/lorax#718]
During a training lab that included Image Builder, some users noted that finding the package they were looking for was harder than expected when the results that were returned from filtering this list included package names that did not start with value provided by the user.

The sort order should instead display all items that start with the value first, followed by all items that do not start with the value. 

For example, filtering the packages using "libvirt" **currently produces the following**:
- fenc-virtd-libvirt
- libvirt
- libvirt-admin
- (a bunch of items that match libvirt*)
- pcp-pmda-libvirt
- python3-libvirt

With this change, filtering the packages using "libvirt" is **expected to produce the following**:
- libvirt
- libvirt-admin
- (a bunch of items that match libvirt*)
- fenc-virtd-libvirt >>> this is no longer before packages that start with "libvirt"
- pcp-pmda-libvirt
- python3-libvirt

**Comment by bcl** [comment]
The API returns the sorted list of items containing libvirt, if you want to display them in a different order then I think the UI is going to have to re-sort them. I don't think this kind of sorting decision belongs in the back-end since it is really a presentation issue.

**Comment by larskarlitski** [comment]
> The API returns the sorted list of items containing libvirt, if you want to display them in a different order then I think the UI is going to have to re-sort them. I don't think this kind of sorting decision belongs in the back-end since it is really a presentation issue.

This doesn't work in the general case, because the returned list is paginated. The frontend can't fetch all the matches for "python" and resort them, because there are 3864 of them and only the first few are returned.

For this case though, it works: the frontend prefixes and suffixes an asterisk. Removing the one at the start should effectively do what Jenn is asking about.

However, the API documentation doesn't mention that shell-style globbing is supported at all. I assume anything that `dnf(8)` documents under **SPECIFYING PACKAGES** is supported?

**Comment by bcl** [comment]
We are passing it to dnf's glob filter - https://dnf.readthedocs.io/en/latest/api_queries.html?highlight=glob#dnf.query.Query.filter so yes, shell-style globbing, but I'm not sure if the rest of that dnf manpage section applies.

Good point about pages, I'd forgotten about that. But still, this isn't the kind of thing the backend should decide. If the UI need to tweak the presentation it will need to either combine globs or fetch them all and do it's own paging.
