### ISSUE TITLE
tests: We're not catching errors in test scripts

### ISSUE THREAD

**Issue by larskarlitski** [weldr/lorax#727]
beakerlib doesn't seem to fail when there's an error in the test script. I'm not sure if we can just `set -e`, because that would kill the test process and might not produce the status report.

To reproduce, call an unknown command in one of the test scripts. I noticed it in https://github.com/weldr/lorax/pull/720

**Comment by martinpitt** [comment]
Put any cleanup action and the status report into a `trap` handler. It's *really* not optional to run a test without `set -e`.

**Comment by atodorov** [comment]
beakerlib is not designed to do this. I remember they had docs in their man pages (but can't remember which one) that the surrounding test harness needs to evaluate the results and report failures. Since we are not using the test harness we do this on our own:
https://github.com/weldr/lorax/blob/master/tests/test_cli.sh#L93


Not using Beaker's test harness (beah) mostly because we run some of the scripts on Ubuntu in Travis CI. For RHEL/Fedora/CentOS we can install that and run the scripts through the harness I think.

Another alternative is to examine the results in `tearDown` inside the Python test classes.

**Comment by larskarlitski** [comment]
@atodorov This is not about test failures, but about errors in the script itself. Do you mind if I add `set -e` (as @martinpitt suggested)? This will catch simple oversights such as "command not found". We have been bitten a few times by this unfortunately.

**Comment by atodorov** [comment]
@larskarlitski you mean adding `set -e` to all of the bash scripts, right? 

I don't mind but maybe we can add something to `test_cli.sh` to fail if the test scripts exit with non zero.

**Comment by larskarlitski** [comment]
> I don't mind but maybe we can add something to `test_cli.sh` to fail if the test scripts exit with non zero.

`set -e` would take care of that as well.
