### ISSUE TITLE
live-cd: can't log in

### ISSUE THREAD

**Issue by larskarlitski** [weldr/lorax#731]
After creating a live-iso, I cannot log in as `liveuser` (no password, right?) nor as `root`.

I've noticed this because `test_compose_live-iso.sh` doesn't work. The image is created, but the test can't log in via ssh. I'm disabling the test for now.

**Comment by bcl** [comment]
This will be fixed by my live iso  PR #726

**Comment by larskarlitski** [comment]
> This will be fixed by my live iso PR #726

Ah cool. Adding a `Closes #731` to the commit message of that pull request would have closed this issue automatically once it landed.

**Comment by larskarlitski** [comment]
#726 did not fix this unfortunately.

**Comment by atodorov** [comment]
@larskarlitski - is this the same as https://bugzilla.redhat.com/show_bug.cgi?id=1710877 ?

That is are you able to login with root on the terminal vs. not able to login via SSH ? So far we've figured out that we don't get the network up and running and this is why the test failed.

**Comment by larskarlitski** [comment]
Thanks for the pointer. I don't know how related these are. I'm seeing the same ssh failure as in the bug you linked.

But I also cannot boot the resulting machine and log in as `liveuser` with no password.

**Comment by bcl** [comment]
Have you re-tried this? It should be working, at least it does for me.

**Comment by atodorov** [comment]
> I've noticed this because test_compose_live-iso.sh doesn't work. 

I've noticed something similar recently but when I run the test manually on a system in Beaker. I think the problem here is that when I do this I'm on a actual terminal and the first ssh command (auth with password), which is supposed to terminate just opens a prompt and waits indefinitely for me to enter a password. 

I think in other environments this doesn't happen. Haven't tried how that happens in Cockpit CI.

**Comment by codygarver** [comment]
I've been experiencing this since switching my F29 live CD build to F30 beta and beyond, my kickstarts are based on [official Fedora Kickstarts](https://pagure.io/fedora-kickstarts). Let me know if I can provide any useful logs or other info.

**Comment by Conan-Kudo** [comment]
I'm having similar problems with livecd-creator, which makes me suspicious that something is broken with the kickstarts, but I can't quite pin down what's wrong...

**Comment by bcl** [comment]
The important part of #726 was to make sure initscripts is in the kickstart, otherwise the live scripts don't run at boot time and the liveuser isn't created. Failing that the next most likely reason for login failure is usually selinux. Try booting with selinux=0 and see if that helps (and if so, file a bug with selinux)

**Comment by Conan-Kudo** [comment]
It does work with `selinux=0` with lcc, not sure if lmc is similarly afflicted.
