### ISSUE TITLE
Re-enable lorax/azure test

### ISSUE THREAD

**Issue by atodorov** [weldr/lorax#763]
https://github.com/cockpit-project/cockpit/pull/12059

FTR next time use `@unittest.skip` instead of disabling in a different repository b/c it is hard to see that this is disabled.

**Comment by larskarlitski** [comment]
> FTR next time use `@unittest.skip` instead of disabling in a different repository b/c it is hard to see that this is disabled.

Good point. I didn't do that because
1. We were blocking an image refresh (they're gated on lorax' tests) and it was quicker to get a review there.
2. I thought that this way we can still trigger them manually when needed. However, a PR that fixes the issue could remove the skip, so that point is a bit moot. Just didn't think about it :)

Does the test work again?

**Comment by atodorov** [comment]
I've re-enabled this test on the cockpit side of things, see:
https://github.com/cockpit-project/cockpit/pull/12645

and added @skip in our source code in #841.

Still need to enable the test and adjust the infra & creds properly.

**Comment by bcl** [comment]
azure tests are working now.
