### ISSUE TITLE
Python test suite: call API via HTTP

### ISSUE THREAD

**Issue by atodorov** [weldr/lorax#764]
While discussing https://github.com/weldr/lorax/pull/747 with @larskarlitski  he told me that the existing Python test suite doesn't actually invoke the API via HTTP (like a standard client will do) but short-circuits internally (if I understood this correctly).

This is why he added an integration test for CORS headers.

I haven't looked into the Python test site in details so at this time I'm not quite sure how it works exactly but filing this issue here so it is not forgotten and so we can investigate and decide whether or not we want to change.

CC @bcl

**Comment by bcl** [comment]
I don't think this is an actual problem -- we are using the flask test client (see http://flask.pocoo.org/docs/0.12/testing/), I don't think there is any benefit to repeating all of those tests via the socket, unless we find a situation where the results would be different.

**Comment by larskarlitski** [comment]
There's no need to do the work to repeat them, indeed.

We definitely need at least some integration tests that verify the full stack on an installed lorax-composer.

**Comment by bcl** [comment]
Right, do the API specific tests using the client test framework, do an integration test that uses the full stack to make sure the socket -> server connection is working. The current cli tests have that pretty well covered I think, they are using composer-cli to build images before booting them and checking them so that's a complete test.

**Comment by atodorov** [comment]
Based on the last comment closing this.
