### ISSUE TITLE
Add more kickstart sanity checks to livemedia-creator

### ISSUE THREAD

**Issue by bcl** [weldr/lorax#79]
lmc really only supportst part / --size=<blah> not autopart, lvm, or --grow, etc. lmc should catch these before trying to start anaconda.

**Comment by roadfox** [comment]
Does this mean that an LVM configuration with lorax is not possible?

i tried this:
`
part /boot --fstype="xfs" --size=512

# Create an LVM partition
part pv.pv00 --size=1024 --grow
volgroup vg00 --pesize=4096 pv.pv00

logvol / --fstype="xfs" --name="lv_root" --vgname="vg00" --size=200000
logvol /home --fstype="xfs" --name="lv_home" --vgname="vg00" --size=2000
logvol /var --fstype="xfs" --name="lv_var" --vgname="vg00" --size=5000
`

and i always get "name already in use" i think due to the fact that lorax is addin a "disk / --size" somewhere, also the vmdk i try to build is much too small.

Can i build an LVM based image?
Is it possible to workarround by spezifyinf the vmdk disk size and do the partitioning in kickstart?
Or should i do something different?

thanks

**Comment by bcl** [comment]
Were you trying with --no-virt? And which image type?
I think it *might* be possible to make a partitioned-disk image with lvm, as long as you use virt to do it, but I'm not sure without trying it myself.

**Comment by roadfox** [comment]
Sorry for my late reply, strange times...

I'm calling the composer like this:
composer-cli compose start rhel7-base vmdk

what does the --no-virt do? could not find it in the documentation on https://weldr.io/lorax/composer-cli.html#build-an-image

also how do i handle my changes to the kickstart file, they get overwritten by a upgrade or reinstall? i could not find the right way to define my custom kickstart file

my biggest problem at the moment is that lorax adds a "disk / size=something" to the final kickstart which seems then to be used to define the size of the vmdk. but the size is far to small and does not take into account all the size definitions of the lvm partitions

**Comment by bcl** [comment]
Oh, so you're using lorax-composer, that's a different thing that builds on top of livemedia-creator. You cannot control the partitioning at all when using lorax-composer.

Neither of them parse the LVM commands when examining the kickstart, I'd forgotten about that in my previous reply, so this really won't work.
